### ISSUE TITLE
AttributeError: type object 'Model' has no attribute 'from_hbjson'

### ISSUE THREAD

**Issue by snjsomnath** [ladybug-tools/dragonfly-energy#817]
https://github.com/ladybug-tools/dragonfly-energy/blob/07431651bb2ec2cc8da004d26eb9d81c088ee6d9/dragonfly_energy/cli/translate.py#L305C24-L305C24

CLI fails to create gbxml
>>
`AttributeError: type object 'Model' has no attribute 'from_hbjson'`

`from dragonfly.model import Model`

should be

`from honeybee.model import Model`

or better yet, why re-form the model while hb_model has already been created?

**Comment by chriswmackey** [comment]
Thanks for reporting the issue, @snjsomnath . This is a part of the code that I have not used in a while so I would bet that your diagnosis of the bug is correct. Let me take a deeper look and push a fix.

**Comment by chriswmackey** [comment]
Actually, taking a deeper look, I think you might misunderstand the purpose of this command since it is working as designed for me:
![image](https://github.com/ladybug-tools/dragonfly-energy/assets/5567574/59947889-7259-46eb-a4d9-571f2c6e18c9)

The command is meant to translate a Dragonfly Model as a DFJSON to gbXML. Not a HBJSON. I think the command you are looking for to translate a HBJSON is this one:
**https://www.ladybug.tools/honeybee-energy/docs/cli/translate.html#honeybee-energy-translate-model-to-gbxml**

I added some more information in the help text of the dragonfly CLI to make this clear:
https://github.com/ladybug-tools/dragonfly-energy/pull/818

... and I also added support for sending a HBJSON to these Dragonfly commands with the caveat that the HBJSON geometry will get simplified to meet the Dragonfly geometry schema.

**Comment by snjsomnath** [comment]
@chriswmackey Sorry about getting back to this so late and for not being specific in how to recreate the bug. I think the issue still exists. 
passing `model-to-gbxml unnamed.dfjson --output-file unnamed.xml` will execute without errors since it is using the `--minimal` option by default that does not invoke the line I mentioned in the error.

Could you please try it again using the `--full-geometry` option. 

```
        if minimal:
            _run_translation_osw(osw, out_path)
        else:
            _, idf = run_osw(osw, silent=True)
            if idf is not None and os.path.isfile(idf):
                hb_model = Model.from_hbjson(hb_model_json)
                add_gbxml_space_boundaries(out_f, hb_model)
                if out_path is not None:  # load the JSON string to stdout
                    with open(out_path) as json_file:
                        print(json_file.read())
```
`Model.from_hbjson` in this context is called to add the space boundaries to the HBJson to then generate the gbxml.
